#!/usr/bin/env python
# Super simple script that listens to a local UDP port and relays all packets to an arbitrary remote host.
# Works with Python 2 and 3

import sys, socket, os, signal, errno, time, argparse

DEBUG=False

def fail(reason):
	sys.stderr.write(reason + '\n')
	sys.exit(1)

def writePidFile(pidFileName):
	if pidFileName == None:
		return

	try:
		f = open(pidFileName, "w")
		f.write(str(os.getpid()))
		f.close()
	except:
		fail('Could not write PID to ' + pidFileName)

def removePidFile(pidFileName):
	if pidFileName == None:
		return

	try:
		os.remove(pidFileName)
	except OSError, ex:
		if ex.errno != 2:
			sys.stderr.write("#%i Failed to remove PID file %s\n" % (int(ex.errno), pidFileName))

def writeOutput(fileName, message):
	message = "%s: '%s'" % (time.strftime("%Y-%m-%d %H:%M:%S"), message)
	
	if fileName == '-':
		print(message)
	else:
		out = open(fileName, "a")
		out.write(message + "\n")
		out.close()
		
def signalTermHandler (signum, frame):
	global pidFile

	if pidFile != None:
		removePidFile(pidFile)

	sys.exit(0)

parser = argparse.ArgumentParser(description='udp-echo writes incoming UDP messages to STDOUT or file')
parser.add_argument('-p', '--port', help='Local port number to listen', required=True, type=int)
parser.add_argument('-l', '--lock', help='Lock/PID file path', required=False, default=None)
parser.add_argument('-o', '--output', help='Output file path, if unspecified outputs to STDOUT', required=False, default='-')

args = parser.parse_args()

localPort = args.port
pidFile = args.lock
outputFile = args.output

try:
	s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	s.bind(('', localPort))
except:
	fail('Failed to bind on port ' + str(localPort))

if pidFile != None:
	writePidFile(pidFile)

if DEBUG:
	sys.stderr.write('All set.\n')

signal.signal(signal.SIGTERM, signalTermHandler)
signal.signal(signal.SIGINT , signalTermHandler) 

while True:
	try:
		data, addr = s.recvfrom(32768)
	except:
		if pidFile != None:
			removePidFile(pidFile)

		# Normal termination
		sys.exit(0)

	writeOutput(outputFile, data)
